### ISSUE TITLE
Consulta sobre esCiclope()

### ISSUE THREAD

**Issue by AntonioDLC** [pdepjm/parcial-minions#1]
Hola, abro este issue porque revisando la solución me entró una duda.

`esCiclope() `es usada para determinar la dificultad que tiene para un empleado defender un sector.
Pero ¿no se dijo que era preferible evitar preguntar por la clase de un objeto?

Por eso ¿no habíamos hecho en clase una solución en la que se le preguntaba directamente al empleado su `factorDebilidad()` que retorna 1 en cualquier caso menos el del Ciclope, en el que retornaba 2 y así la dificultad se calculaba `gradoDeAmenaza*empleado.factorDebilidad()`?

**Comment by asanzo** [comment]
Tenés razón, ahí lo arreglo :)

Hacé click en el commit de abajo para ver los cambios.
