### ISSUE TITLE
Un detalle

### ISSUE THREAD

**Issue by AntonioDLC** [pdepjm/parcial-minions#2]
La mucama debería overridear el método `puedeDefender() `para que devuelva` false`.

**Comment by asanzo** [comment]
Hola, Antonio!

Hagamos una cosa: animate a hacer tu aporte. ¡Es código abierto!

Pasos:

1) Hacé un fork del proyecto en tu propio usuario.

![seleccion_018](https://user-images.githubusercontent.com/5421992/32555635-1be54562-c47c-11e7-93f7-4f816a4df148.png)

Según veo, esto ya lo hiciste.

2) Sobre ese repositorio el tuyo propio, tu propio fork, podés hacer los commits y cambios que quieras.

3) Cuando tenés todo commiteado y pusheado en tu propio repo, hacés click en "Create Pull Request" (en tu propio repo). 

![seleccion_019](https://user-images.githubusercontent.com/5421992/32555862-a18048d4-c47c-11e7-8a77-0743cc7f58f9.png)

4) El 4to paso lo tengo que hacer yo. Me va a llegar tu pull request, y yo lo reviso y lo acepto :)

¡Y tendrás tu primera colaboración hecha a código libre!

**Comment by AntonioDLC** [comment]
Ahhh fenómeno.
Ahí va.

**Comment by asanzo** [comment]
Felicitaciones :)
